#!/bin/bash

cut -f 1 -d ":" test > tmpfl
cut -f 2 -d ":" test > tmpva

paste tmpva tmpfl | awk 'BEGIN{acc=0; dif=0; tot=0; best=0; fl5=0}
{print int(3.33986 - 0.09088 * $1 + 0.5); }' > regres_test_predict_detail
 
rm tmpfl tmpva
