#!/bin/bash

# vypise accurancy a pocet lisicich se o jedna

awk 'BEGIN{acc=0; dif=0; tot=0; best=0; fl5=0}
{if ($1-$2==1 || $1-$2==-1) dif++;
 if ($1==$2) acc++;
 if ($1 == "5" && $2 == "5") best++;
 if ($2 == "5") fl5++;
 tot++;}
END{
 print "Presna shoda: " (acc/tot)*100 " % (" acc "/" tot ")"; 
 print "Shoda nebo +-1: " ((dif+acc)/tot)*100 " % (" dif+acc "/" tot ")"; 
 print "Shoda v plynulosti 5: " ((best/fl5)*100) " % (" best "/" fl5 ")";
 }'
